import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import PopUp from '../components/ChatWidget/PopUp'
import Message from '../components/ChatWidget/Modules/Message'
import { useRef, useState,useEffect, useCallback } from 'react'

export default function Home() {


    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
           
        </main>
        <PopUp/>
        </>
    )
}
